name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 #https://knowledge.udacity.com/questions/821482#822258
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=2.11.0 #https://knowledge.udacity.com/questions/821482#822258
  - pyarrow=2.0
  - jinja2=3.0.3  #https://knowledge.udacity.com/questions/821482#822258
  - pip:
      - wandb==0.12.17 #https://knowledge.udacity.com/questions/854897